query GetTeacherSchedule($code: String!) {
  teacher(code: $code) {
    name
    schedule {
      monday {
        slot 
        subject
        room
        type
        teacher
      }
      tuesday {
        slot
        subject
        room
        type
        teacher
      } 
      wednesday {
        slot
        subject
        room
        type
        teacher
      }
      thursday {
        slot
        subject
        room
        type
        teacher
      }
      friday {
        slot
        subject
        room
        type
        teacher
      }
    }
  }
}
